name: "Connect Publish (dev)"
on:
  push:
    branches: [main]

jobs:
  connect-publish:
    name: connect-publish-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Publish to RStudio Connect (and render)
        shell: bash
        env:
          QUARTO_PRINT_STACK: true
          CONNECT_SERVER: ${{ secrets.RSCONNECT_URL }}
          CONNECT_API_KEY: ${{ secrets.RSCONNECT_API_KEY }}
        run: |
          git config --global user.email "quarto-github-actions-publish@example.com"
          git config --global user.name "Quarto GHA Workflow Runner"
           
          quarto publish --id a59059a0-c72a-4cd8-8843-5a4929821e2f --no-browser